* Fall 2020 - Lab 07

* Last name:

* First name:

* GitHub username:

* Notes:



* General instructions:
- Fill in your name and GitHub username on top.
- Use the Notes section to add any notes to the instructor.
- The main lab description can be found here:
  https://maryash.github.io/135/labs/lab_07.html 


* Important changes in this lab.

This lab will be graded differently than the other labs and has
slightly different specifications. You are required to use a
*Makefile* that builds an executable named *main* that will run the
program but I will not grade the lab through the tests. That said, you
should create doctest based tests where appropriate to test portions
of your solution.

Your program must also be built from multiple files (that is, not
everything in main.cpp). You should name them appropriately. This
repo starts with funcs.h and funcs.cpp merely as examples. You can use
them if you think best or remove them (don't forget to ~git remove~
them if you do use other filenames) and use files with other names. 

*Important:* The main lab has you create multiple separate programs
 (unindent.cpp, indent.cpp). You should only have one executable. Your
 final program should take input from stdin (cin) (just as the main lab page
 indicates), perform both tasks and print the output to stdout (cout).
